### PR TITLE
Added reverse to fix #20

### LINKED ISSUE #20: wheel reverse scrolling direction
Im using trackball on mac / windows(PC)

It is uncomfortable because the wheels are in different directions.
By any chance, can you add options?

Thank you.

### PR DESCRIPTION
**Pull request by ArmanHayots**
This time it's OK.
Also please check some `WARN:` comments in State.cs.

### CODE REVIEW

**Comment by Seelge** [comment]
Thanks for your pull request, I'll review & test the changes during the week.

> isn't a-(a/b)*b equals to zero?

Not with integer division.

**Comment by ArmanHayots** [comment]
> Not with integer division

Ooops, I forgot about that.

**Comment by Seelge** [comment]
@ArmanHayots 
Review: Your changes look good but there seems to be a line ending mismatch causing entire files to be unnecessarily changed. The affected files are:
Settings.Designer.cs
Settings.settings
Can you fix the line endings?

**Comment by ArmanHayots** [comment]
@Seelge 
Which line endings must be used? 
VS using windows (CRLF), git usually automatically converts them to unix (LF).
I've disabled autoconversion for now, but still don't know which LE-s must be used in project.

**Comment by Seelge** [comment]
The repository had an inconsistent line ending style. With commit 724371 all line endings are LF.

**Comment by Seelge** [comment]
Just merged the PR, thanks for your contribution.

**Comment by ArmanHayots** [comment]
No need to thank me, 'cause I've done nothing.

**Pull request merged**
